// ═══════════════════════════════════════════════════════════════
// DEMO DATA — High Risk Impact System Examples
// Real-world case scenarios for testing
// ═══════════════════════════════════════════════════════════════

/**
 * Demo Case 1: HIGH RISK - PEP with High-Risk Country Exposure
 * Real scenario: Politician from Syria with structured deposits
 */
const demoCase_HighRisk_001 = {
  caseId: 'EDD-2026-001',
  customerName: 'Karim Al-Rashid',
  customerType: 'Individual',
  riskCategory: 'HIGH',
  riskSource: 'External Risk Classifier (QIB Risk Engine)',
  dateClassified: '2026-03-09',
  
  /* Current Risk Exposure */
  pepStatus: true,
  pepType: 'Politician - Former Government Official',
  pepSource: 'External PEP Database (Global Watchlist Monitor)',
  
  countryRisk: {
    level: 'High',
    name: 'Syria',
    reason: 'OFAC Listed Country'
  },
  
  occupationRisk: {
    level: 'High',
    category: 'Arms & Defense Sector (Listed)',
    details: 'Self-employed consultant - unverified'
  },
  
  activityFlags: [
    'Structured Deposits (< $10k threshold)',
    'Round-number transactions',
    'Timing pattern suspicious (weekly deposits)'
  ],
  
  productRisk: {
    level: 'High',
    name: 'Political Multi-currency Account',
    reason: 'High-risk jurisdiction + PEP status'
  },
  
  documentationScore: 65,
  
  /* Missing Documentation */
  sourceOfWealthDoc: 'Missing',
  salaryDoc: 'Missing',
  passportExpiry: '2026-01-15',
  identityVerified: true,
  addressVerified: false,
  
  /* Potential Consequences */
  /* Generated by system */
  
  /* Recommended Actions */
  /* Generated by system */
  
  /* Investigation Status */
  daysOpen: 18,
  investigator: 'Ahmed Al-Mansouri',
  status: 'Under Investigation'
};

/**
 * Demo Case 2: HIGH RISK - Auto-detected Missing Evidence + Flags
 * Scenario: Customer with high-risk profile but insufficient documentation
 */
const demoCase_HighRisk_002 = {
  caseId: 'EDD-2026-002',
  customerName: 'Mohammed Al-Khalifa',
  customerType: 'Individual',
  riskCategory: 'HIGH',
  riskSource: 'System Auto-Detection (Missing SOF + Activity Flags)',
  dateClassified: '2026-03-08',
  
  pepStatus: false,
  
  countryRisk: {
    level: 'Medium',
    name: 'United Arab Emirates',
    reason: 'Standard monitoring'
  },
  
  occupationRisk: {
    level: 'Medium',
    category: 'Import/Export Business',
    details: 'Trade finance sector'
  },
  
  activityFlags: [
    'Large cash deposits (AED 500k+ monthly)',
    'Frequent international wire transfers',
    'Mixed business and personal use'
  ],
  
  productRisk: {
    level: 'Medium',
    name: 'Standard Trade Finance Account',
    reason: 'Activity mismatch with declared purpose'
  },
  
  documentationScore: 52,
  
  sourceOfWealthDoc: 'Missing',
  salaryDoc: 'Available (12 months)',
  passportExpiry: '2027-06-30',
  identityVerified: true,
  addressVerified: true,
  
  daysOpen: 12,
  investigator: 'Fatima Al-Mansoori',
  status: 'Under Investigation'
};

/**
 * Demo Case 3: MEDIUM RISK - Requires Verification
 * Scenario: Age-appropriate documentation + travel patterns
 */
const demoCase_MediumRisk_001 = {
  caseId: 'EDD-2026-003',
  customerName: 'Sara Al-Maktoum',
  customerType: 'Individual',
  riskCategory: 'MEDIUM',
  riskSource: 'Manual Assessment',
  dateClassified: '2026-03-07',
  
  pepStatus: false,
  
  countryRisk: {
    level: 'Low',
    name: 'Canada',
    reason: 'Standard market'
  },
  
  occupationRisk: {
    level: 'Medium',
    category: 'International Student',
    details: 'Studying Business at University'
  },
  
  activityFlags: [
    'Student account (educational transfers)',
    'Periodic deposits from parent sponsor',
    'Low transaction volume'
  ],
  
  productRisk: {
    level: 'Low',
    name: 'Student Checking Account',
    reason: 'Age-appropriate for profile'
  },
  
  documentationScore: 88,
  
  sourceOfWealthDoc: 'Available (Parent sponsor declaration)',
  salaryDoc: 'N/A (Student)',
  passportExpiry: '2028-12-31',
  identityVerified: true,
  addressVerified: true,
  
  daysOpen: 5,
  investigator: 'Hassan Al-Dhaheri',
  status: 'Awaiting Review'
};

/**
 * Demo Case 4: LOW RISK - Normal Customer
 * Scenario: Routine KYC completion
 */
const demoCase_LowRisk_001 = {
  caseId: 'EDD-2026-004',
  customerName: 'Abdullah Al-Mazrouei',
  customerType: 'Individual',
  riskCategory: 'LOW',
  riskSource: 'Standard KYC Assessment',
  dateClassified: '2026-02-15',
  
  pepStatus: false,
  
  countryRisk: {
    level: 'Low',
    name: 'United Arab Emirates',
    reason: 'Standard market'
  },
  
  occupationRisk: {
    level: 'Low',
    category: 'Executive - Local Company',
    details: 'CFO at National Oil Company'
  },
  
  activityFlags: [],
  
  productRisk: {
    level: 'Low',
    name: 'Standard Salary Account',
    reason: 'Regular employment income'
  },
  
  documentationScore: 100,
  
  sourceOfWealthDoc: 'Available (Employment contract)',
  salaryDoc: 'Available (Recent)',
  passportExpiry: '2029-09-12',
  identityVerified: true,
  addressVerified: true,
  
  daysOpen: 0,
  investigator: 'System Auto-Approved',
  status: 'Completed - Approved'
};

/**
 * Dashboard Demo Data
 * Aggregated metrics
 */
const demoDashboardMetrics = {
  totalHighRiskCases: 8,
  casesWithMissingEvidence: 5,
  topRiskDrivers: {
    pepDetected: 3,
    highRiskCountry: 4,
    missingSOF: 5
  },
  slaAtRisk: 2,
  totalOpenCases: 24
};

/**
 * Sample Audit Log
 */
const sampleAuditLog = [
  {
    timestamp: '2026-03-11T14:32:00Z',
    eventType: 'HIGH_RISK_PANEL_VIEWED',
    caseId: 'EDD-2026-001',
    userId: 'ahmed.mansouri',
    actionShown: 7,
    details: 'User viewed High Risk Impact panel'
  },
  {
    timestamp: '2026-03-11T14:35:22Z',
    eventType: 'ACTION_COMPLETED',
    caseId: 'EDD-2026-001',
    userId: 'ahmed.mansouri',
    actionId: 'ACT004',
    action: 'Escalate: Confirm PEP status with external data provider',
    completed: true,
    details: 'Investigator marked action as completed'
  },
  {
    timestamp: '2026-03-11T15:08:00Z',
    eventType: 'HIGH_RISK_PANEL_VIEWED',
    caseId: 'EDD-2026-002',
    userId: 'fatima.mansoori',
    actionShown: 6,
    details: 'User viewed High Risk Impact panel'
  }
];

/**
 * Initialize Demo Data
 * Use in browser console:
 * initializeDemoData();
 */
function initializeDemoData() {
  window.demoData = {
    cases: {
      highRisk1: demoCase_HighRisk_001,
      highRisk2: demoCase_HighRisk_002,
      mediumRisk1: demoCase_MediumRisk_001,
      lowRisk1: demoCase_LowRisk_001
    },
    dashboard: demoDashboardMetrics,
    auditLog: sampleAuditLog
  };

  console.log('Demo Data Loaded:', window.demoData);
  return window.demoData;
}

/**
 * Get sample case by ID
 * @param {string} caseId - Case ID
 * @returns {Object} - Case data
 */
function getSampleCase(caseId) {
  const allCases = [
    demoCase_HighRisk_001,
    demoCase_HighRisk_002,
    demoCase_MediumRisk_001,
    demoCase_LowRisk_001
  ];

  return allCases.find(c => c.caseId === caseId) || null;
}

/**
 * Get all HIGH RISK cases
 * @returns {Array} - Array of high risk cases
 */
function getHighRiskCases() {
  return [
    demoCase_HighRisk_001,
    demoCase_HighRisk_002
  ];
}

/**
 * Export for modules
 */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    demoCase_HighRisk_001,
    demoCase_HighRisk_002,
    demoCase_MediumRisk_001,
    demoCase_LowRisk_001,
    demoDashboardMetrics,
    sampleAuditLog,
    initializeDemoData,
    getSampleCase,
    getHighRiskCases
  };
}

// Auto-initialize on load
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initializeDemoData);
} else {
  initializeDemoData();
}
